[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
flaek_mb = "9H2L2RwoURMv9pVaW2TWx6uasFuHg4PYW92jaVVDaicW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".anchor/test-wallet.json"

[scripts]
test = "node -r ts-node/register ./node_modules/mocha/bin/_mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
